### ISSUE TITLE
記事の取得について

### ISSUE THREAD

**Issue by hgleam** [uraway/hatena-blog-entry-post#27]
最新のver4.2.5ですが、Index Entriesの機能は正しく動作しますでしょうか？
hatena-blog-and-fotolife-modelのclient.indexが2度呼ばれています(想定通り？)。

1度目は期待通りの値が取得できているように見えますが2度目にエラーを返して
くるため、記事の取得に失敗しているようです。

確認いただけないでしょうか？

**Comment by uraway** [comment]
コメントありがとうございます。こちらで確認したところ、Index Entriesは正しく動作しました。

>hatena-blog-and-fotolife-modelのclient.indexが2度呼ばれています(想定通り？)。

二度呼ぶことはないはずです。ただ、依存ライブラリとこのパッケージのconsole内容がダブることはありえます。

API Key、Blog URL、Hatena ID といった設定は正しく入力されてますでしょうか？ご確認ください。

もしエラーが続くようでしたら、エラーログをレポートしていただければ助かります！

**Comment by hgleam** [comment]
なるほど、私もconsole.logで確認して
みただけでしたので上記のような確認を
取らせてもらった次第です(詳細に確認した
わけではありませんが・・・)。

また、記事の作成は出来るので、APIキー、
Blog URL Hatena IDに間違いはないと
いう認識です。なぜか記事の取得のみ
出来ません。

エラーログですがatomのデベロッパーツール
のログで問題ないでしょうか？

**Comment by uraway** [comment]
> エラーログですがatomのデベロッパーツール
のログで問題ないでしょうか？

はい。お手数ですが、お願いできますか。

**Comment by hgleam** [comment]
エラー画面を添付いたします。
ご確認お願いいたします。

![image](https://user-images.githubusercontent.com/3738479/43028887-8803a50e-8cbd-11e8-8b9a-abbe8a0ca183.png)

**Comment by uraway** [comment]
ありがとうございます！無事バグを見つけて修正することができました！
おそらく直っているはずなので、最新バージョンのv4.2.6をお試しください~

**Comment by hgleam** [comment]
改善されたこと確認できました。
迅速な対応ありがとうございました。
